[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
